### PR TITLE
Add 'uih' as bin command so consumers can just call 'uih' after installing to run

### PR DESCRIPTION
**Pull request by frederickfogerty**

### CODE REVIEW

**Comment by philcockfield** [comment]
I've always found the `bin` documentation on NPM to be frustratingly limited - mostly because I really want it to work differently to what it actually does.  But I might not be understanding it.

Can you confirm - this will put `uih` as an available command IF the UIHarness is installed globally, right?

    npm install -g ui-harness

That's the behavior I've got working - but am I missing something about being able to call `uih` locally within a folder if it has a bin declared?  It doesn't work that way, by my reckoning, is that right @frederickfogerty 

If that's the case - then I've been thinking about a fuller command line API for UIHarness (using [CommanderJS](https://github.com/tj/commander.js/)), so we'd have something along the lines of:

    uih start

Which would start the UIHarness in the current folder.  But also the other commands would be available (with full man pages) such as `uih build`

Am I missing something about how `bin` works @frederickfogerty ?

**Comment by frederickfogerty** [comment]
> Can you confirm - this will put uih as an available command in the terminal IF the UIHarness is installed globally, right?

Yes it will.

> That's the behavior I've got working - but am I missing something about being able to call uih locally within a folder if it has a bin declared? It doesn't work that way, by my reckoning, is that right @frederickfogerty

I think you've got it wrong here. Calling `uih` will first check `/usr/local/bin` or equivalent for `uih`, which is where the global `ui-harness` would install too, but then it also checks for `./node_modules/.bin`, which is where a local (read: module dependency) install would put the executable. 

Thus, if package maintainers installed `ui-harness` as a dependency, then others would be able to run it with `uih` **without** installing it globally.

I can verify this because I haven't installed `ui-harness` globally yet I can use it in my projects by just calling `uih`.

**Comment by philcockfield** [comment]
Well, heck!  That is damn useful if it behaves like that.  That's how I wanted it to behave.

I propose that we put the actual `uih` command line here, not just the start method.  I'm pulling this PR now, and will stub in what I'm thinking.

**Comment by philcockfield** [comment]
OK - just played around trying to get it to work the way you said it does.  It's not playing nicely - so I must being doing something stupid.

I'll get you to show me what you're doing when we chat later on @frederickfogerty, if you would.

**Comment by philcockfield** [comment]
Confirmed with @frederickfogerty that NPM doesn't work this way (ALAS!!!....it damn well should).

**Pull request closed without merging**
